// Code generated by options-gen. DO NOT EDIT.
package database

import (
	fmt461e464ebed9 "fmt"
	"log/slog"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	parser computeParser,
	storage storage,
	logger *slog.Logger,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.parser = parser

	o.storage = storage

	o.logger = logger

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("parser", _validate_Options_parser(o)))
	errs.Add(errors461e464ebed9.NewValidationError("storage", _validate_Options_storage(o)))
	errs.Add(errors461e464ebed9.NewValidationError("logger", _validate_Options_logger(o)))
	return errs.AsError()
}

func _validate_Options_parser(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.parser, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `parser` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_storage(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.storage, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `storage` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_logger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.logger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `logger` did not pass the test: %w", err)
	}
	return nil
}
