# https://taskfile.dev

version: '3'

vars:
  WORKDIR:
    sh: echo "$(pwd)"

  DEV_TOOLS: |
    github.com/kazhuravlev/options-gen/cmd/options-gen@v0.33.0
    go.uber.org/mock/mockgen@v0.4.0
    golang.org/x/tools/cmd/stringer
    
  DEV_TOOLS_PATH: /tools/bin

tasks:
  generate:
    cmds:
      - export PATH=$PATH:{{.WORKDIR}}{{.DEV_TOOLS_PATH}} && go generate ./...

  dev-tools:install:
    cmds:
      - echo "- Install dev tools"
      - mkdir -p .{{.DEV_TOOLS_PATH}}
      - |
        {{range $tool := .DEV_TOOLS | trim | splitLines -}}
          GOBIN={{$.WORKDIR}}{{$.DEV_TOOLS_PATH}} go install {{$tool}}
        {{end -}}
