// Code generated by options-gen. DO NOT EDIT.
package storage

import (
	fmt461e464ebed9 "fmt"
	"log/slog"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	engine engineStore,
	logger *slog.Logger,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.engine = engine

	o.logger = logger

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("engine", _validate_Options_engine(o)))
	errs.Add(errors461e464ebed9.NewValidationError("logger", _validate_Options_logger(o)))
	return errs.AsError()
}

func _validate_Options_engine(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.engine, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `engine` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_logger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.logger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `logger` did not pass the test: %w", err)
	}
	return nil
}
